services:
  postgres:
    image: postgres:latest
    container_name: 3dFarm_Postgress
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: 3dFarm
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql